spring.application.name=alumnos
server.port=8080

# conexion a Supabase con SSL obligatorio
spring.datasource.url=jdbc:postgresql://aws-0-eu-west-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.tadlkdjxojonynvcbajf
spring.datasource.password=D2298jdawoiddwi!

# validate comprueba que las entidades coinciden con las tablas, no las modifica
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
